### ISSUE TITLE
Error: Cannot determine the module for class HomePage 

### ISSUE THREAD

**Issue by mohsinmr** [dreamhouseapp/dreamhouse-mobile-ionic#12]
On executing ```ionic cordova build android --prod``` to generate **APK**,  it is producing following error: 

```
Running app-scripts build: --prod --platform android --target cordova
[14:46:06]  build prod started ... 
[14:46:06]  clean started ... 
[14:46:06]  clean finished in 3 ms 
[14:46:06]  copy started ... 
[14:46:06]  ngc started ... 
Error: Cannot determine the module for class HomePage in /Users/mohsinrasheed/ionic-projects/test/dreamhouse-mobile-ionic/src/pages/home/home.ts! Add HomePage to the NgModule to fix it.
Cannot determine the module for class ListPage in /Users/mohsinrasheed/ionic-projects/test/dreamhouse-mobile-ionic/src/pages/list/list.ts! Add ListPage to the NgModule to fix it.
    at syntaxError (/Users/mohsinrasheed/ionic-projects/test/dreamhouse-mobile-ionic/node_modules/@angular/compiler/bundles/compiler.umd.js:1513:34)
    at analyzeAndValidateNgModules (/Users/mohsinrasheed/ionic-projects/test/dreamhouse-mobile-ionic/node_modules/@angular/compiler/bundles/compiler.umd.js:22424:15)
    at AotCompiler.compileAll (/Users/mohsinrasheed/ionic-projects/test/dreamhouse-mobile-ionic/node_modules/@angular/compiler/bundles/compiler.umd.js:22197:18)
    at CodeGenerator.codegen (/Users/mohsinrasheed/ionic-projects/test/dreamhouse-mobile-ionic/node_modules/@angular/compiler-cli/src/codegen.js:30:14)
    at Function.NgTools_InternalApi_NG_2.codeGen (/Users/mohsinrasheed/ionic-projects/test/dreamhouse-mobile-ionic/node_modules/@angular/compiler-cli/src/ngtools_api.js:61:30)
    at Object.doCodegen (/Users/mohsinrasheed/ionic-projects/test/dreamhouse-mobile-ionic/node_modules/@ionic/app-scripts/dist/aot/codegen.js:6:51)
    at /Users/mohsinrasheed/ionic-projects/test/dreamhouse-mobile-ionic/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:42:30
    at <anonymous>

```

**Comment by Dr-VegaPunk** [comment]
when you create a page using

ionic g page new (ionic 1 or 2)

first you need to import it in app.module.ts file

import { NewPage } from '../pages/new/new';

and add it  in declarations array and entryComponents array

declarations: [
    MyApp,
    HomePage,
    ListPage,
    NewPage
  ],
  entryComponents: [
    MyApp,
    HomePage,
    ListPage,
    NewPage
  ],

declarations : In the declarations section we need to include all components and directives we create.If we don't include them here, we'll get an error when we try to use them because Angular won't be able to recognise them in our code.

entryComponents: In the entryComponents section we define any component that is only loaded by its type. This is the case for all Page components since these are all loaded through the Navigation Controller.

Components that are loaded declaratively don't need to be included in the entryComponents array. So as you can see we have some duplication where we have to define our Page components in both the declarations and the entryComponents sections. The reason for having this separate entryComponents section is so that Angular can compile a bundle for the app that will only include the components that are actually used within the app.

------------------------------------------------------------------------------------------

I would recommend using lazy loading since it removes the need to repeatedly import pages everywhere and speeds the app (more pages declared means more time for angular to compile them...), no need for imports or anything simply create the page by using this command in terminal : 
ionic g page new (ionic 3)

now that your page is created, lets say your are in you HomePage and you want to go to NewPage : 
this.navCtrl.push('NewPage');  

Voila!

For more information : http://masteringionic.com/blog/2017-04-14-lazy-loading-with-ionic-3/
