### ISSUE TITLE
Error: Cannot find module 'D:\ionic\myapp\dreamhouse-mobile-ionic\node_modules\@ ionic\app-scripts\bin\ionic-app-scripts.js'

### ISSUE THREAD

**Issue by nikhilrmusale** [dreamhouseapp/dreamhouse-mobile-ionic#3]
i installed it ! but when i fire command **'ionic serve'** it gives me 

> ionic-app-scripts build

module.js:472
    throw err;
    ^

Error: Cannot find module 'D:\ionic\myapp\dreamhouse-mobile-ionic\node_modules\@
ionic\app-scripts\bin\ionic-app-scripts.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3

**Comment by ffelaar** [comment]
run `npm install @ionic/app-scripts@latest --save-dev`
